### ISSUE TITLE
Latest v2.0 POM not deployed to Maven Central

### ISSUE THREAD

**Issue by jycchoi** [unitsofmeasurement/uom-lib#44]
The latest v2.0 POM file (tech.uom.lib:uom-lib:2.0) was not deployed to Maven Central.  It is the parent POM for the Common Library (tech.uom.lib:uom-lib-common:2.0), making the maven resolution failed.

**Comment by keilw** [comment]
Thanks for spotting that. Unfortunately a bug in MavenCentral/Sonatype does not show the 2.0 Final releases as newest version, but this one wasn't synced. Will do right now.

**Comment by keilw** [comment]
It's there now, 5 versions of uom-lib on MavenCentral, the PRD being listed as "latest" is a bug by Sonatype, you see it correct on Bintray.
