### ISSUE TITLE
tech.uom.lib:uom-lib-jackson:2.0 is not published

### ISSUE THREAD

**Issue by xspeedcruiser** [unitsofmeasurement/uom-lib#51]
I am unable to find tech.uom.lib:uom-lib-jackson:2.0 in maven central

**Comment by keilw** [comment]
Because it has not been released yet, so far it is "2.0-SNAPSHOT", please use the following enhancement in your POM:
<repositories>
		<repository>
			<snapshots>
				<enabled>false</enabled>
			</snapshots>
			<id>bintray-release</id>
			<name>libs-release</name>
			<url>http://oss.jfrog.org/artifactory/libs-release</url>
		</repository>
		<repository>
			<snapshots>
				<enabled>true</enabled>
			</snapshots>
			<id>bintray-snapshot</id>
			<name>libs-snapshot</name>
			<url>http://oss.jfrog.org/artifactory/libs-snapshot</url>
		</repository>
		<repository>
			<id>jcenter</id>
			<name>JCenter</name>
			<url>http://jcenter.bintray.com</url>
		</repository>
</repositories>

**Comment by ddcruver** [comment]
Any updates on this?

**Comment by keilw** [comment]
This is done https://bintray.com/unitsofmeasurement/maven/tech.uom.lib%3Auom-lib-jackson/2.0 it should also be on MavenCentral within a few hours.
