### ISSUE TITLE
Version 2.0 of the assertJ library not published to jcenter and maven central

### ISSUE THREAD

**Issue by SanderSmee** [unitsofmeasurement/uom-lib#57]
When checking available versions of the assertJ library, version 2.0 is not available at maven central, or jcenter.

For example check the following URL at maven central search: https://search.maven.org/artifact/tech.uom.lib/uom-lib-assertj

**Comment by keilw** [comment]
There was a failure at Sonatype or Bintray itself which is why it could not get synchronized. The version is declared but it did not propogate the files. Hope they fixed it by now, will try again later today.

**Comment by keilw** [comment]
There was another problem with MavenCentral sync, but after deleting the version from Bintray and signing everything again it finally worked. Should be also in MavenCentral in a few hours.

**Comment by SanderSmee** [comment]
I verified the existence of the artifact at maven central. Thank you for resolving the issue.
