### ISSUE TITLE
Serialization of units with "per square" content

### ISSUE THREAD

**Issue by fawidmer** [unitsofmeasurement/uom-lib#68]
The following minimum example displays:
```
"m2"
"m/s"
"V2/Ohm"
"Ohm/V"
```

However, I'd expect something like:
```
"m2"
"m/s2"
"V2/Ohm"
"Ohm/V2"
```

It seems like this issue only happens for units with a negative exponent. Units like square meter seem to work fine.

Our dependencies:
```xml
<dependency>
    <groupId>tech.units</groupId>
    <artifactId>indriya</artifactId>
    <version>2.0.4</version>
</dependency>

<dependency>
    <groupId>tech.uom.lib</groupId>
    <artifactId>uom-lib-jackson</artifactId>
    <version>2.0.1</version>
</dependency>
```

**Sample code:**

```java
import javax.measure.Unit;
import javax.measure.quantity.Acceleration;
import javax.measure.quantity.Area;

import org.junit.Test;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;

import tech.units.indriya.unit.Units;
import tech.uom.lib.jackson.UnitJacksonModule;

public class TempTest {

    @Test
    public void test() throws JsonProcessingException {
        Unit<Area> areaUnit = Units.SQUARE_METRE;
        Unit<Acceleration> accelUnit = Units.METRE_PER_SQUARE_SECOND;
        Unit<?> composedUnit = Units.VOLT.pow(2).divide(Units.OHM);
        Unit<?> composedUnitInverted = composedUnit.inverse();

        ObjectMapper mapper = new ObjectMapper();
        mapper.registerModule(new UnitJacksonModule());

        System.out.println(mapper.writeValueAsString(areaUnit));
        System.out.println(mapper.writeValueAsString(accelUnit));
        System.out.println(mapper.writeValueAsString(composedUnit));
        System.out.println(mapper.writeValueAsString(composedUnitInverted));
    }

}
```

**Comment by fawidmer** [comment]
@keilw: I was just checking the status of this issue and was very happy to see that you recently added some labels. Please feel free to contact me at any time if you need further information!

**Comment by keilw** [comment]
@fawidmer Basically I added some more labels like JSON for both the Jackson and Yasson (Jakarta JSON Binding) modules. There also is a RI ticket https://github.com/unitsofmeasurement/indriya/issues/352 which I recently transferred from the API because it could be related to Indriya, but it also includes this library, so not completely impossible they have something to do with each other.

**Comment by keilw** [comment]
@fawidmer Please check out the 2.1 version of uom-lib-jackson just released last night.

**Comment by fawidmer** [comment]
@keilw: Seems to be working perfectly now, thanks a lot for your help!!
